name: Auto Add Files

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: autocommit
  cancel-in-progress: true

jobs:
  add-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update files (WIB)
        run: |
          git pull --rebase
          mkdir -p update
          rm -rf update/*
          TS=$(date +'%Y-%m-%d_%H-%M')
          echo "$(TZ='Asia/Jakarta' date)" > update/$TS.txt
          echo "$(TZ='Asia/Jakarta' date)" >> file.txt
          echo "Last update: $(TZ='Asia/Jakarta' date)" > README.md

      - name: Commit and push
        run: |
          git add .
          git commit -m "auto: $(date +'%Y-%m-%d_%H-%M-%S')" || echo "No changes"
          git push
