name: Auto Add Files

on:
  schedule:
    - cron: '*/2 * * * *'  # Menjalankan commit otomatis setiap 2 menit
  push:
    branches:
      - master  # Ubah dengan nama cabang yang sesuai jika diperlukan

jobs:
  add-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Add current date and time to file.txt in WIB
        run: |
          rm -rf ./update/*
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M')
          echo "$(git rev-parse --short HEAD)" > ./timestamp/$TIMESTAMP.txt
          echo "$(TZ='Asia/Jakarta' date)" >> file.txt
          git add *  # Menambahkan yang telah dimodifikasi

      - name: Commit changes
        run: |
          TS=$(date +"%Y-%m-%d_%H-%M-%S")
          git config --global user.name "syawalokta"
          git config --global user.email "syawaloktasyahputra@gmail.com"
          git commit -m $TS
          git push
