name: Auto Add Files

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: autocommit
  cancel-in-progress: true

jobs:
  add-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update files (WIB)
        run: |
          mkdir -p update
          rm -rf update/*
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M')
          echo "$(TZ='Asia/Jakarta' date)" > update/$TIMESTAMP.txt
          echo "$(TZ='Asia/Jakarta' date)" >> file.txt
          echo "Last update: $(TZ='Asia/Jakarta' date)" > README.md

      - name: Commit and push
        run: |
          git pull --rebase
          git add .
          TS=$(date +"%Y-%m-%d_%H-%M-%S")
          git commit -m "auto: $TS" || echo "No changes"
          git push
