name: second acc

on:
  schedule:
    - cron: '*/5 * * * *'  # Menjalankan commit otomatis setiap 5 menit
  push:
    branches:
      - master  # Ubah dengan nama cabang yang sesuai jika diperlukan

jobs:
  add-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "EdopVilone"
          git config --global user.email "edopjunior14@gmail.com"

      - name: Update files
        run: |
          rm -rf ./2/*
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M')
          echo "Last updated: $(TZ='Asia/Jakarta' date) by davidpangrib001" > ./README.md
          echo "$(TZ='Asia/Jakarta' date)" > ./2/$TIMESTAMP.txt
          echo "$(TZ='Asia/Jakarta' date)" >> 2.txt
          git add *  # Menambahkan yang telah dimodifikasi

      - name: Commit changes
        run: |
          TS=$(date +"%Y-%m-%d_%H-%M-%S")
          git commit -m $TS
          git push

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GHT_TOKEN }}  # Token akses GitHub otomatis
        run: git push
